implementing functions to create, delete and convert snapshots

diff --git a/backup-vm b/backup-vm
--- a/backup-vm
+++ b/backup-vm
@@ -56,11 +56,11 @@ function get_qemu_version {
     qemu_version=$(${rpm_bin} -q qemu-img |cut -d"-" -f3|cut -d"." -f1)
 
     if [ "${qemu_version}" -ge 3 ]; then
-        qemu_options="-WcO qcow2"
+        qemu_options="-f raw -WcO qcow2"
         log_message "info" "qemu version ${qemu_version} or higher detected"
         log_message "info" "using options ${qemu_options}"
     else
-        qemu_options="-cO qcow2"
+        qemu_options="-f raw -cO qcow2"
         log_message "info" "qemu version ${qemu_version} or lower detected"
         log_message "info" "using options ${qemu_options}"
     fi
@@ -105,13 +105,13 @@ function make_config_backup {
     log_message "error" "Error creating configuration backup in ${NFSEXPORT}/${vm}-${timestamp}/${vm}.xml"
     exit 4
   fi
-  vm_definition_file="${NFSEXPORT}/${vm}-${timestamp}/${vm}.xml"
 }
 
 function get_disks {
   log_message "info" "Getting disks"
   for disk in $(virsh domblklist --details "${vm}"|awk '/dev/ {print $4}' | xargs); do
     disks+=("${disk}")
+    disks_names+=("${disk##*/}")
     log_message "info" "Disks: ${disk} found for vm ${vm}"
   done
 }
@@ -120,7 +120,7 @@ function get_vgs {
   log_message "info" "Getting volumes groups"
   for disk in "${disks[@]}"; do
     vgs+=( "$(lvdisplay -v "${disk}" 2>/dev/null|awk '/VG/ {print $3}')" )
-    disk_size+=( "$(lvdisplay -v "${disk}" 2>/dev/null|awk '/LV Size/ {print $3}')" )
+    disk_size+=( "$(lvdisplay -v "${disk}" 2>/dev/null|awk '/LV Size/ {print $3}'|awk -F"." '{print $1}')" )
   done
   for ((i=0; i<${#vgs[@]}; i++)); do
     log_message "info" "Volume group ${vgs[$i]} found for disk ${disks[$i]} with size ${disk_size[$i]}"
@@ -130,36 +130,93 @@ function get_vgs {
 function get_vm_status {
   log_message "info" "Getting vm status"
   vm_status=$(virsh domstate "${vm}")
-  log_message "info" "vm ${vm} status is ${vm_status}"
 }
 
 function shutdown_vm {
-  log_message "info" "Shutting down virtual machine ${vm}"
-  if ! virsh shutdown "${vm}" &>/dev/null; then
-    log_message "error" "Error shutting down virtual machine ${vm}"
-    exit 5
-  fi
-  log_message "info" "Waiting ${TIME_SHUTDOWN} seconds for virtual machine ${vm} to shutdown"
-  sleep "${TIME_SHUTDOWN}"
   get_vm_status
+  if [ "${vm_status}" = "shut off" ]; then
+    log_message "info" "Virtual machine ${vm} is ${vm_status}"
+  else
+    log_message "info" "Virtual machine ${vm} is ${vm_status}"
+    log_message "info" "Shutting down virtual machine ${vm}"
+    if ! virsh shutdown "${vm}" &>/dev/null; then
+      log_message "error" "Error shutting down virtual machine ${vm}"
+      exit 5
+    fi
+    log_message "info" "Waiting ${TIME_SHUTDOWN} seconds for virtual machine ${vm} to shutdown"
+    sleep "${TIME_SHUTDOWN}"
+    get_vm_status
+  fi
 }
 
 function start_vm {
   log_message "info" "Starting virtual machine ${vm}"
   if ! virsh start "${vm}" &>/dev/null; then
     log_message "error" "Error starting virtual machine ${vm}"
-    exit 6
+    exit 7
   fi
-  get_vm_status
 }
 
+function take_snapshot {
+  for ((i=0; i<${#disks[@]}; i++)); do
+    vg_free_space=$(vgdisplay "${vgs[$i]}" | awk '/Free/ {print $7}'|awk -F"." '{print $1}')
+    log_message "info" "Checking volume group ${vgs[$i]} for free space"
+    if [ "${vg_free_space}" -gt "${disk_size[$i]}" ]; then
+      log_message "info" "Volume group ${vgs[$i]} has enough free space to take snapshot"
+      if ! lvcreate -s -n "${disks_names[$i]}Snap" -L "${disk_size[$i]}G" "${disks[$i]}" 2>/dev/null; then
+        log_message "error" "Error taking snapshot of virtual machine ${vm}"
+      exit 8
+    fi
+    else
+      log_message "error" "Volume group ${vgs[$i]} has not enough free space to take snapshot"
+      delete_snapshots
+      start_vm
+      exit 8
+    fi
+  done
+  start_vm
+}
+
+function delete_snapshots {
+  log_message "info" "Deleting snapshot ${disks_names[$i]}Snap"
+  snapshots=$(lvdisplay |grep Snap|awk '/Path/ {print $3}' |xargs)
+  if ! lvremove -f "${snapshots}" 2>/dev/null; then
+    log_message "error" "Error deleting snapshot of virtual machine ${vm}"
+    exit 9
+  fi
+}
+
+function convert_to_qcow2 {
+  for snap in "${snapshots}"; do
+    snap_name=$(echo "${snap}" | awk -F"/" '{print $NF}')
+    log_message "info" "Converting snapshot ${snap} to qcow2"
+    if ! qemu-img convert ${qemu_options} "${snap}" "${NFSEXPORT}/${vm}-${timestamp}/${snap_name}.qcow2"; then
+      log_message "error" "Error converting snapshot ${snap} to qcow2"
+      delete_snapshots
+      exit 10
+    fi
+    delete_snapshots
+  done
+}
+
+function main {
+  load_config
+  get_qemu_version
+  check_vm_exists
+  prepare_dirs
+  make_config_backup
+  get_disks
+  get_vgs
+  shutdown_vm
+  if [ "${vm_status}" = "shut off" ]; then
+    take_snapshot
+    convert_to_qcow2
+  else
+    log_message "info" "Virtual machine ${vm} is not shut off"
+    exit 6
+  fi
+  exit 0
+}
 
 # Main Script
-load_config
-get_qemu_version
-check_vm_exists
-prepare_dirs
-make_config_backup
-get_disks
-get_vgs
-shutdown_vm
+main
